// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guiywabvamigjugagggl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1aXl3YWJ2YW1pZ2p1Z2FnZ2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjQ3MzksImV4cCI6MjA1NzMwMDczOX0.1O7dlo5-Exxd5zRDrAJVs_jmm-ACeakzW2AwYdQmy7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);